src/Entity/Salons.php
<?php

namespace App\Entity;

use App\Repository\SalonsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SalonsRepository::class)
 */
class Salons
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Calendar::class, inversedBy="salons")
     * @ORM\JoinColumn(nullable=true)
     */
    private $calendar;

    /**
     * @ORM\ManyToOne(targetEntity=FashionWeeks::class, inversedBy="salons")
     */
    private $fashion_weeks;

    /**
     * @ORM\ManyToOne(targetEntity=SalonType::class, inversedBy="salons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $salon_type;

    /**
     * @ORM\ManyToOne(targetEntity=SaisonsMode::class, inversedBy="salons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $saison_mode;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link_salon_digital;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link_exposants;

    /**
     * @ORM\Column(type="boolean")
     */
    private $publish_online;

    /**
     * @ORM\Column(type="boolean")
     */
    private $publish_map;

    /**
     * @ORM\OneToMany(targetEntity=CampaignDesigner::class, mappedBy="salon", orphanRemoval=true)
     */
    private $campaignDesigners;

    /**
     * @ORM\OneToMany(targetEntity=CampaignShowroom::class, mappedBy="salon")
     */
    private $campaignShowrooms;

    /**
     * @ORM\OneToMany(targetEntity=FilActu::class, mappedBy="salon")
     */
    private $filActus;

    /**
     * @ORM\OneToMany(targetEntity=EventProdServices::class, mappedBy="salon")
     */
    private $eventProdServices;

    public function __construct()
    {
        $this->campaignDesigners = new ArrayCollection();
        $this->campaignShowrooms = new ArrayCollection();
        $this->filActus = new ArrayCollection();
        $this->eventProdServices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCalendar(): ?Calendar
    {
        return $this->calendar;
    }

    public function setCalendar(?Calendar $calendar): self
    {
        $this->calendar = $calendar;

        return $this;
    }

    public function getFashionWeeks(): ?FashionWeeks
    {
        return $this->fashion_weeks;
    }

    public function setFashionWeeks(?FashionWeeks $fashion_weeks): self
    {
        $this->fashion_weeks = $fashion_weeks;

        return $this;
    }

    public function getSalonType(): ?SalonType
    {
        return $this->salon_type;
    }

    public function setSalonType(?SalonType $salon_type): self
    {
        $this->salon_type = $salon_type;

        return $this;
    }

    public function getSaisonMode(): ?SaisonsMode
    {
        return $this->saison_mode;
    }

    public function setSaisonMode(?SaisonsMode $saison_mode): self
    {
        $this->saison_mode = $saison_mode;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    public function getLinkSalonDigital(): ?string
    {
        return $this->link_salon_digital;
    }

    public function setLinkSalonDigital(?string $link_salon_digital): self
    {
        $this->link_salon_digital = $link_salon_digital;

        return $this;
    }

    public function getLinkExposants(): ?string
    {
        return $this->link_exposants;
    }

    public function setLinkExposants(?string $link_exposants): self
    {
        $this->link_exposants = $link_exposants;

        return $this;
    }

    public function getPublishOnline(): ?bool
    {
        return $this->publish_online;
    }

    public function setPublishOnline(bool $publish_online): self
    {
        $this->publish_online = $publish_online;

        return $this;
    }

    public function getPublishMap(): ?bool
    {
        return $this->publish_map;
    }

    public function setPublishMap(bool $publish_map): self
    {
        $this->publish_map = $publish_map;

        return $this;
    }

    /**
     * @return Collection|CampaignDesigner[]
     */
    public function getCampaignDesigners(): Collection
    {
        return $this->campaignDesigners;
    }

    public function addCampaignDesigner(CampaignDesigner $campaignDesigner): self
    {
        if (!$this->campaignDesigners->contains($campaignDesigner)) {
            $this->campaignDesigners[] = $campaignDesigner;
            $campaignDesigner->setSalon($this);
        }

        return $this;
    }

    public function removeCampaignDesigner(CampaignDesigner $campaignDesigner): self
    {
        if ($this->campaignDesigners->removeElement($campaignDesigner)) {
            // set the owning side to null (unless already changed)
            if ($campaignDesigner->getSalon() === $this) {
                $campaignDesigner->setSalon(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|CampaignShowroom[]
     */
    public function getCampaignShowrooms(): Collection
    {
        return $this->campaignShowrooms;
    }

    public function addCampaignShowroom(CampaignShowroom $campaignShowroom): self
    {
        if (!$this->campaignShowrooms->contains($campaignShowroom)) {
            $this->campaignShowrooms[] = $campaignShowroom;
            $campaignShowroom->setSalon($this);
        }

        return $this;
    }

    public function removeCampaignShowroom(CampaignShowroom $campaignShowroom): self
    {
        if ($this->campaignShowrooms->removeElement($campaignShowroom)) {
            // set the owning side to null (unless already changed)
            if ($campaignShowroom->getSalon() === $this) {
                $campaignShowroom->setSalon(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|FilActu[]
     */
    public function getFilActus(): Collection
    {
        return $this->filActus;
    }

    public function addFilActu(FilActu $filActu): self
    {
        if (!$this->filActus->contains($filActu)) {
            $this->filActus[] = $filActu;
            $filActu->setSalon($this);
        }

        return $this;
    }

    public function removeFilActu(FilActu $filActu): self
    {
        if ($this->filActus->removeElement($filActu)) {
            // set the owning side to null (unless already changed)
            if ($filActu->getSalon() === $this) {
                $filActu->setSalon(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|EventProdServices[]
     */
    public function getEventProdServices(): Collection
    {
        return $this->eventProdServices;
    }

    public function addEventProdService(EventProdServices $eventProdService): self
    {
        if (!$this->eventProdServices->contains($eventProdService)) {
            $this->eventProdServices[] = $eventProdService;
            $eventProdService->setSalon($this);
        }

        return $this;
    }

    public function removeEventProdService(EventProdServices $eventProdService): self
    {
        if ($this->eventProdServices->removeElement($eventProdService)) {
            // set the owning side to null (unless already changed)
            if ($eventProdService->getSalon() === $this) {
                $eventProdService->setSalon(null);
            }
        }

        return $this;
    }
}

templates/admin_calendar/admin_campaign_designer.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
    Moddity | Campaign Designer
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <!-- *************************************************************** -->
        <!-- Start First Cards -->
        <!-- *************************************************************** -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center mb-4">
                            <h4 class="card-title mb-0">Campaign Designer</h4>&nbsp;&nbsp;
                            <a href="{{ path('add_campaign_designer') }}" class="btn btn-primary btn-sm">Add Campaign Designer</a>
                            <div class="ml-auto">
                                <div class="dropdown sub-dropdown">
                                    <button class="btn btn-link text-muted dropdown-toggle" type="button"
                                        id="dd1" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                        <i data-feather="more-horizontal"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dd1">
                                        <a class="dropdown-item" href="{{ path('add_campaign_designer') }}">Add new Campaign Designer</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {# Affichage des messages utilisateur de validation de suppresion #}
                        {% for message in app.flashes('success') %}
                            
                            <div class="col-md-4 bg-success text-center p-2 text-white mx-auto rounded mb-4">
                            {{ message }}
                            </div>

                        {% endfor %}

                        <div class="table-responsive">
                            <table id="table-salons" class="table table-striped table-bordered text-center">
                                <thead>
                                    <tr>
                                        <th scope="col">Designer</th>
                                        <th scope="col">Fashion Weeks</th>
                                        <th scope="col">Publish map</th>
                                        <th scope="col">Saison</th>
                                        <th scope="col">Salon</th>
                                        <th scope="col">Location</th>
                                        <th scope="col">Start Date</th>
                                        <th scope="col">End Date</th>
                                        <th scope="col">Publish online</th>
                                        <th scope="col">Details</th>
                                        <th scope="col">Edit</th>
                                        <th scope="col">Supp</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if CampaignD %}
                                        
                                    {% set i = 1 %}    
                                    {% for data in CampaignD %}
                                        <tr>
                                            <td>{{ data.designer.label }}</td>

                                            {% if data.fashionWeeks %}
                                                <td>{{ data.fashionWeeks.name }}</td>
                                            {% else %}
                                                <td><i class="fas fa-exclamation-triangle text-danger"></i></td>
                                            {% endif %}

                                            {% if data.publishMap == true %}
                                                <td><i class="far fa-check-square text-success"></i></td>
                                            {% else %}
                                                <td><i class="fas fa-exclamation-triangle text-danger"></i></td>
                                            {% endif %}
                                            
                                            <td>{{ data.saison.label }}</td>
                                            <td>{{ data.salon.location }}</td>
                                            <td>{{ data.location }}</td>

                                            <td>{{ data.dateDebut|date('d/m/Y') }}</td>
                                            <td>{{ data.dateFin|date('d/m/Y') }}</td>
                                            {# <td>{{ data.location }}</td>
                                            <td>{{ data.adresse }}</td>
                                            <td>{{ data.ville }}</td>
                                            <td>{{ data.codePostal }}</td>
                                            <td>{{ data.pays }}</td>
                                            <td>{{ data.commentaire }}</td>
                                            <td>{{ data.contact }}</td> #}

                                            {% if data.publishOnline == true %}
                                                <td><i class="far fa-check-square text-success"></i></td>
                                            {% else %}
                                                <td><i class="fas fa-exclamation-triangle text-danger"></i></td>
                                            {% endif %}

                                            <td>
                                                <a href="" class="table-action" type="button" data-toggle="modal" data-target="#modal-campaign-designer{{ i }}">
                                                    <i class="fas fa-eye" data-toggle="tooltip" title="voir les details du salon"></i>
                                                </a>
                                            </td>

                                            <td><a href="{{ path('update_campaign_designer', {'id': data.id}) }}" class="table-action"><i class="fas fa-edit" data-toggle="tooltip" title="Modifier la campaign Designer"></i></a></td>

                                            <td><a href="{{ path('delete_campaign_designer', {'id': data.id}) }}" class="table-action" onclick="return(confirm('Voulez-vous réellement supprimer ce salon ?'));"><i class="fas fa-trash-alt" data-toggle="tooltip" title="Supprimer la campaign Designer ?"></i></a></td>

                                        </tr>

                                        <!--  Modal content for the above example -->
                                        <div class="modal fade" id="modal-campaign-designer{{ i }}" tabindex="-1" role="dialog"
                                            aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title" id="myLargeModalLabel">Salon session</h4>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                            aria-hidden="true">×</button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p class="d-flex justify-content-between">
                                                            <strong>Fashion Week</strong>
                                                            <span>
                                                            {% if data.fashionWeeks %}
                                                                {{ data.fashionWeeks.name }}
                                                            {% else %}
                                                                <i class="fas fa-exclamation-triangle text-danger"></i>
                                                            {% endif %}
                                                            </span>
                                                        </p>
                                                        <p class="d-flex justify-content-between">
                                                            <strong>Publish Map</strong>
                                                            <span>
                                                            {% if data.publishMap == true %}
                                                                <i class="far fa-check-square text-success"></i>
                                                            {% else %}
                                                                <i class="fas fa-exclamation-triangle text-danger"></i>
                                                            {% endif %}
                                                            </span>
                                                        </p>
                                                        <p class="d-flex justify-content-between">
                                                            <strong>Type salon</strong>
                                                            <span>{{ data.salon.location }}</span>
                                                        </p>
                                                        
                                                        <p class="d-flex justify-content-between">
                                                            <strong>Publish Online</strong>
                                                            <span>
                                                            {% if data.publishOnline == true %}
                                                                <i class="far fa-check-square text-success"></i>
                                                            {% else %}
                                                                <i class="fas fa-exclamation-triangle text-danger"></i>
                                                            {% endif %}
                                                            </span>
                                                        </p>
                                                    </div>
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->

                                        {% set i = i + 1 %}

                                    {% endfor %}

                                {% else %}
                                        
                                    <tr>
                                        <td colspan="20">Aucune campaign Designer</td>
                                    </tr>    

                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                  </div>

                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/admin_calendar/admin_campaign_showroom.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
    Moddity | Campaign Showroom
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <!-- *************************************************************** -->
        <!-- Start First Cards -->
        <!-- *************************************************************** -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center mb-4">
                            <h4 class="card-title mb-0">Campaign Showroom</h4>&nbsp;&nbsp;
                            <a href="{{ path('add_campaign_showroom') }}" class="btn btn-primary btn-sm">Add Campaign Showroom</a>
                            <div class="ml-auto">
                                <div class="dropdown sub-dropdown">
                                    <button class="btn btn-link text-muted dropdown-toggle" type="button"
                                        id="dd1" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                        <i data-feather="more-horizontal"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dd1">
                                        <a class="dropdown-item" href="{{ path('add_campaign_showroom') }}">Add new Campaign Showroom</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {# Affichage des messages utilisateur de validation de suppresion #}
                        {% for message in app.flashes('success') %}
                            
                            <div class="col-md-4 bg-success text-center p-2 text-white mx-auto rounded mb-4">
                            {{ message }}
                            </div>

                        {% endfor %}

                        <div class="table-responsive">
                            <table class="table table-striped text-center">
                                <thead class="thead-dark">
                                    <tr>
                                            <th scope="col">Fashion Weeks</th>
                                            <th scope="col">Saison</th>
                                            <th scope="col">Salon</th>
                                    {% for data in colonnes %}

                                        {% if data != 'id' %}

                                            <th scope="col">{{ data }}</th>

                                        {% endif %}

                                    {% endfor %}
                                            <th scope="col">Modifier</th>
                                            <th scope="col">Supprimer</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if CampaignS %}
                                        
                                    {% for data in CampaignS %}
                                        <tr>
                                            {% if data.fashionWeeks %}
                                                <td>{{ data.fashionWeeks.name }}</td>
                                            {% else %}
                                                <td><i class="fas fa-exclamation-triangle text-danger"></i></td>
                                            {% endif %}

                                            <td>{{ data.saison.label }}</td>
                                            <td>{{ data.salon.location }}</td>

                                            {% if data.publishMap == true %}
                                                <td><i class="far fa-check-square text-success"></i></td>
                                            {% else %}
                                                <td><i class="fas fa-exclamation-triangle text-danger"></i></td>
                                            {% endif %}

                                            <td>{{ data.dateDebut|date('d/m/Y H:i:s') }}</td>
                                            <td>{{ data.dateFin|date('d/m/Y H:i:s') }}</td>
                                            <td>{{ data.location }}</td>
                                            <td>{{ data.adresse }}</td>
                                            <td>{{ data.ville }}</td>
                                            <td>{{ data.codePostal }}</td>
                                            <td>{{ data.commentaire }}</td>
                                            <td>{{ data.contact }}</td>

                                            {% if data.publishOnline == true %}
                                                <td><i class="far fa-check-square text-success"></i></td>
                                            {% else %}
                                                <td><i class="fas fa-exclamation-triangle text-danger"></i></td>
                                            {% endif %}

                                            <td><a href="{{ path('update_campaign_showroom', {'id': data.id}) }}" class="table-action"><i class="fas fa-edit" data-toggle="tooltip" title="Modifier la campaign Showroom"></i></a></td>

                                            <td><a href="{{ path('delete_campaign_showroom', {'id': data.id}) }}" class="table-action" onclick="return(confirm('Voulez-vous réellement supprimer cette campaign Showroom ?'));"><i class="fas fa-trash-alt" data-toggle="tooltip" title="Supprimer la campaign Showroom ?"></i></a></td>
                                            
                                        </tr>
                                    {% endfor %}

                                {% else %}
                                        
                                    <tr>
                                        <td colspan="20">Aucune campaign Showroom</td>
                                    </tr>    

                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                  </div>

                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/admin_calendar/admin_form_campaign_designer.html.twig
{% extends "base_admin.html.twig" %}

{% block title %}
    Moddity | 
    
    {% if editMode %}
        Update
    {% else %}
        Add
    {% endif %}
    Campaign Designer
    
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <!-- *************************************************************** -->
        <!-- Start First Cards -->
        <!-- *************************************************************** -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center mb-4">
                            <h4 class="card-title mb-0">
                            {% if editMode %}
                                Update
                            {% else %}
                                Add
                            {% endif %}
                            
                            Campaign Designer</h4>
                            <div class="ml-auto">
                                <div class="dropdown sub-dropdown">
                                    <button class="btn btn-link text-muted dropdown-toggle" type="button"
                                        id="dd1" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                        <i data-feather="more-horizontal"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dd1">
                                        <a class="dropdown-item" href="#">Add Campaign Designer</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div>
                        {{ form_start(formCampaignDesigner) }}

                            {{ form_row(formCampaignDesigner.designer) }}
                            {{ form_row(formCampaignDesigner.fashionWeeks) }}
                            {{ form_row(formCampaignDesigner.publish_map) }}
                            {{ form_row(formCampaignDesigner.saison) }}
                            {{ form_row(formCampaignDesigner.collec) }}
                            {{ form_row(formCampaignDesigner.salon) }}
                            {{ form_row(formCampaignDesigner.products) }}
                            {{ form_row(formCampaignDesigner.date_debut) }}
                            {{ form_row(formCampaignDesigner.date_fin) }}
                            {{ form_row(formCampaignDesigner.location) }}
                            {{ form_row(formCampaignDesigner.adresse) }}
                            {{ form_row(formCampaignDesigner.ville) }}
                            {{ form_row(formCampaignDesigner.code_postal) }}
                            {{ form_row(formCampaignDesigner.pays) }}
                            {{ form_row(formCampaignDesigner.commentaire) }}
                            {{ form_row(formCampaignDesigner.contact) }}
                            {{ form_row(formCampaignDesigner.publish_online) }}

                            <button class="btn btn-primary">
                            {% if editMode %}
                                update
                            {% else %}
                                Save
                            {% endif %}
                            </button>

                        {{ form_end(formCampaignDesigner) }}
                        </div>

                    </div>
                </div>
            </div>
        </div>

{% endblock %}