src/Entity/Salons.php
<?php

namespace App\Entity;

use App\Repository\SalonsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SalonsRepository::class)
 */
class Salons
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Calendar::class, inversedBy="salons")
     * @ORM\JoinColumn(nullable=true)
     */
    private $calendar;

    /**
     * @ORM\ManyToOne(targetEntity=FashionWeeks::class, inversedBy="salons")
     */
    private $fashion_weeks;

    /**
     * @ORM\ManyToOne(targetEntity=SalonType::class, inversedBy="salons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $salon_type;

    /**
     * @ORM\ManyToOne(targetEntity=SaisonsMode::class, inversedBy="salons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $saison_mode;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link_salon_digital;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link_exposants;

    /**
     * @ORM\Column(type="boolean")
     */
    private $publish_online;

    /**
     * @ORM\Column(type="boolean")
     */
    private $publish_map;

    /**
     * @ORM\OneToMany(targetEntity=CampaignDesigner::class, mappedBy="salon", orphanRemoval=true)
     */
    private $campaignDesigners;

    /**
     * @ORM\OneToMany(targetEntity=CampaignShowroom::class, mappedBy="salon")
     */
    private $campaignShowrooms;

    /**
     * @ORM\OneToMany(targetEntity=FilActu::class, mappedBy="salon")
     */
    private $filActus;

    /**
     * @ORM\OneToMany(targetEntity=EventProdServices::class, mappedBy="salon")
     */
    private $eventProdServices;

    public function __construct()
    {
        $this->campaignDesigners = new ArrayCollection();
        $this->campaignShowrooms = new ArrayCollection();
        $this->filActus = new ArrayCollection();
        $this->eventProdServices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCalendar(): ?Calendar
    {
        return $this->calendar;
    }

    public function setCalendar(?Calendar $calendar): self
    {
        $this->calendar = $calendar;

        return $this;
    }

    public function getFashionWeeks(): ?FashionWeeks
    {
        return $this->fashion_weeks;
    }

    public function setFashionWeeks(?FashionWeeks $fashion_weeks): self
    {
        $this->fashion_weeks = $fashion_weeks;

        return $this;
    }

    public function getSalonType(): ?SalonType
    {
        return $this->salon_type;
    }

    public function setSalonType(?SalonType $salon_type): self
    {
        $this->salon_type = $salon_type;

        return $this;
    }

    public function getSaisonMode(): ?SaisonsMode
    {
        return $this->saison_mode;
    }

    public function setSaisonMode(?SaisonsMode $saison_mode): self
    {
        $this->saison_mode = $saison_mode;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    public function getLinkSalonDigital(): ?string
    {
        return $this->link_salon_digital;
    }

    public function setLinkSalonDigital(?string $link_salon_digital): self
    {
        $this->link_salon_digital = $link_salon_digital;

        return $this;
    }

    public function getLinkExposants(): ?string
    {
        return $this->link_exposants;
    }

    public function setLinkExposants(?string $link_exposants): self
    {
        $this->link_exposants = $link_exposants;

        return $this;
    }

    public function getPublishOnline(): ?bool
    {
        return $this->publish_online;
    }

    public function setPublishOnline(bool $publish_online): self
    {
        $this->publish_online = $publish_online;

        return $this;
    }

    public function getPublishMap(): ?bool
    {
        return $this->publish_map;
    }

    public function setPublishMap(bool $publish_map): self
    {
        $this->publish_map = $publish_map;

        return $this;
    }

    /**
     * @return Collection|CampaignDesigner[]
     */
    public function getCampaignDesigners(): Collection
    {
        return $this->campaignDesigners;
    }

    public function addCampaignDesigner(CampaignDesigner $campaignDesigner): self
    {
        if (!$this->campaignDesigners->contains($campaignDesigner)) {
            $this->campaignDesigners[] = $campaignDesigner;
            $campaignDesigner->setSalon($this);
        }

        return $this;
    }

    public function removeCampaignDesigner(CampaignDesigner $campaignDesigner): self
    {
        if ($this->campaignDesigners->removeElement($campaignDesigner)) {
            // set the owning side to null (unless already changed)
            if ($campaignDesigner->getSalon() === $this) {
                $campaignDesigner->setSalon(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|CampaignShowroom[]
     */
    public function getCampaignShowrooms(): Collection
    {
        return $this->campaignShowrooms;
    }

    public function addCampaignShowroom(CampaignShowroom $campaignShowroom): self
    {
        if (!$this->campaignShowrooms->contains($campaignShowroom)) {
            $this->campaignShowrooms[] = $campaignShowroom;
            $campaignShowroom->setSalon($this);
        }

        return $this;
    }

    public function removeCampaignShowroom(CampaignShowroom $campaignShowroom): self
    {
        if ($this->campaignShowrooms->removeElement($campaignShowroom)) {
            // set the owning side to null (unless already changed)
            if ($campaignShowroom->getSalon() === $this) {
                $campaignShowroom->setSalon(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|FilActu[]
     */
    public function getFilActus(): Collection
    {
        return $this->filActus;
    }

    public function addFilActu(FilActu $filActu): self
    {
        if (!$this->filActus->contains($filActu)) {
            $this->filActus[] = $filActu;
            $filActu->setSalon($this);
        }

        return $this;
    }

    public function removeFilActu(FilActu $filActu): self
    {
        if ($this->filActus->removeElement($filActu)) {
            // set the owning side to null (unless already changed)
            if ($filActu->getSalon() === $this) {
                $filActu->setSalon(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|EventProdServices[]
     */
    public function getEventProdServices(): Collection
    {
        return $this->eventProdServices;
    }

    public function addEventProdService(EventProdServices $eventProdService): self
    {
        if (!$this->eventProdServices->contains($eventProdService)) {
            $this->eventProdServices[] = $eventProdService;
            $eventProdService->setSalon($this);
        }

        return $this;
    }

    public function removeEventProdService(EventProdServices $eventProdService): self
    {
        if ($this->eventProdServices->removeElement($eventProdService)) {
            // set the owning side to null (unless already changed)
            if ($eventProdService->getSalon() === $this) {
                $eventProdService->setSalon(null);
            }
        }

        return $this;
    }
}

src/Controller/AdminProfileController.php
<?php

namespace App\Controller;

use App\Entity\ProProfile;
use App\Form\ProProfileType;
use App\Repository\ProProfileRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdminProfileController extends AbstractController
{

      /**
     * @Route("/admin/", name="admin")
     */
    public function admin(): Response
    {

        return $this->render('admin_profile/index.html.twig', [
            
        ]);
    }


    /**
     * @Route("/admin/profiles/all", name="admin_profiles_all")
     */
    public function adminProfiles(ProProfileRepository $repo): Response
    {

        $profiles = $repo -> findBy(['type' => [
            'designer', 'boutique', 'showroom'
        ]]);

        return $this->render('admin_profile/profile_list.html.twig', [
            'profiles' => $profiles
        ]);
    }

    

    /**
     * @Route("/admin/profiles/{type}", name="admin_profiles_type")
     */
    public function adminProfilesType($type, ProProfileRepository $repo): Response
    {

        $profiles = $repo -> findBy(['type' => $type]);

        return $this->render('admin_profile/profile_list.html.twig', [
            'profiles' => $profiles
        ]);
    }


    /**
     * @Route("/admin/externals/all", name="admin_externals_all")
     */
    public function adminExternals(ProProfileRepository $repo): Response
    {

        $profiles = $repo -> findBy(['type' => [
            'communication', 'production', 'service'
        ]]);

        return $this->render('admin_profile/profile_list.html.twig', [
            'profiles' => $profiles
        ]);
    }

    /**
     * @Route("/admin/externals/{type}", name="admin_externals_type")
     */
    public function adminExternalsType($type, ProProfileRepository $repo): Response
    {

        $profiles = $repo -> findBy(['type' => $type]);

        return $this->render('admin_profile/profile_list.html.twig', [
            'profiles' => $profiles
        ]);
    }
    /**
     * @Route("/admin/profiles_add", name="admin_profiles_add")
     */
    public function adminProfileAdd(EntityManagerInterface $manager): Response
    {
        $pp = new ProProfile; 
        $form = $this -> createForm(ProProfileType::class, $pp,[]);
       
        return $this -> render('admin_profile/add_form.html.twig', [
            'form' => $form -> createView(),
        ]); 
    }
}

templates/admin_profile/add_form.html.twig
{% extends 'base_admin.html.twig' %}

{% block content %}

<!-- ============================================================== -->
    <div class="container-fluid">
        <!-- *************************************************************** -->
        <!-- Start First Cards -->
        <!-- *************************************************************** -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center mb-4">
                            <h4 class="card-title">Pro Profiles</h4>
                        </div>
                        <div class="table-responsive">

                            {{ form_start(form) }}
                            {{ form_rest(form) }}

                            <input type="input" class="btn btn-success" value="Add" />
                            {{ form_end(form) }}

                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>


{% endblock %}

templates/admin_profile/index.html.twig
{% extends 'base_admin.html.twig' %}

templates/admin_profile/profile_list.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Hello AdminUserController!{% endblock %}

{% block content %}
   
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- *************************************************************** -->
        <!-- Start First Cards -->
        <!-- *************************************************************** -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center mb-4">
                            <h4 class="card-title">Pro Profiles</h4>
                            <div class="ml-auto">
                                <div class="dropdown sub-dropdown">
                                    <button class="btn btn-link text-muted dropdown-toggle" type="button"
                                        id="dd1" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                        <i data-feather="more-horizontal"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dd1">
                                        <a class="dropdown-item" href="#">Add new Pro Profile</a>
                                        <a class="dropdown-item" href="#">Add new Service profile</a>
                                        <a class="dropdown-item" href="#">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table no-wrap v-middle mb-0">
                                <thead>
                                    <tr class="border-0">
                                        <th class="border-0 font-14 font-weight-medium text-muted">#</th>
                                        <th class="border-0 font-14 font-weight-medium text-muted">Email</th>
                                        <th class="border-0 font-14 font-weight-medium text-muted">Services</th>
                                        <th class="border-0 font-14 font-weight-medium text-muted">Ville</th>
                                        <th class="border-0 font-14 font-weight-medium text-muted">Status</th>
                                        <th class="border-0 font-14 font-weight-medium text-muted">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                 {% for profile in profiles %}
                                    <tr>
                                        
                                        <td class="border-top-0 px-2 py-4">
                                            <div class="d-flex no-block align-items-center">
                                                {% set photoPath =  'admin_panel/images/users/widget-table-pic1.jpg' %}
                                                {% if profile.photos %}
                                                  {%  for photo in profile.photos %}
                                                    {% if photo.position == 1 %}
                                                      {% set photoPath =  'upload/img/' ~ photo.name %}
                                                    {% endif %}
                                                  {% endfor %}
                                                {% endif %}
                                                <div class="mr-3"><img
                                                        src="{{ asset(photoPath )}}"
                                                        alt="user" class="rounded-circle" width="45"
                                                        height="45" data-toggle="tooltip" title="ID {{ profile.id }}" />
                                                </div>
                                                <div class="">
                                                    <h5 class="text-dark mb-0 font-16 font-weight-medium">{{ profile.label }}</h5>
                                                    <span class="text-muted font-14">{{ profile.type }}</span>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="border-top-0 text-muted px-2 py-4 font-14">{{ profile.emailMAin }}</td>
                                        <td class="border-top-0 px-2 py-4">
                                            <div class="popover-icon">
                                              {% if profile.users %}
                                                  {%  for user in profile.users %}
                                                    <a class="btn btn-primary rounded-circle btn-circle font-12"
                                                    href="javascript:void(0)" data-toggle="tooltip" title="{{ user.fname }} {{ user.lname }} {{ user.email }}"><i data-feather="user-check" class="feather-icon"></i></a>
                                                  {% endfor %}
                                                {% endif %}


                                                {% if profile.subPlan %}

                                                    {% if profile.subPlan.uuid == 0 %}

                                                    {% elseif profile.subPlan.uuid == 1 %}

                                                    {% else %}
                                                    <a class="btn btn-warning rounded-circle btn-circle font-12 popover-item"
                                                    href="javascript:void(0)" data-toggle="tooltip" title="Sub Plan : {{ profile.subPlan.label }} - {{ profile.subPlan.period }} - {{ profile.subPlan.price }}€"><i data-feather="dollar-sign" class="feather-icon"></i></a>
                                                    {% endif %}
                                                
                                                
                                                 {% endif %}




                                                <a class="btn btn-danger rounded-circle btn-circle font-12 popover-item"
                                                    href="javascript:void(0)" data-toggle="tooltip" title="Production: xxxxxx"><i data-feather="layers" class="feather-icon"></i></a>
                                                <a class="btn btn-cyan rounded-circle btn-circle font-12 popover-item"
                                                    href="javascript:void(0)" data-toggle="tooltip" title="Communication: xxxxxx"><i data-feather="share-2" class="feather-icon"></i></a>
                                                <a class="btn btn-success text-white rounded-circle btn-circle font-20"
                                                    href="javascript:void(0)">+</a>
                                            </div>
                                        </td>
                                        <td class="border-top-0 text-center px-2 py-4">{{ profile.zipCode }} {{ profile.city }}</td>
                                        <td
                                            class="border-top-0 text-center font-weight-medium text-muted px-2 py-4">
                                            <i
                                                class="fa fa-circle text-primary font-12" data-toggle="tooltip"
                                                data-placement="top" title="In Testing"></i>
                                        </td>
                                        <td class="font-weight-medium text-dark border-top-0 px-2 py-4">
                                          <div class="dropdown sub-dropdown">
                                            <button class="btn btn-link text-muted dropdown-toggle" type="button"
                                                id="dd1" data-toggle="dropdown" aria-haspopup="true"
                                                aria-expanded="false">
                                                <i data-feather="more-vertical"></i>
                                            </button>
                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dd1">
                                                <a class="dropdown-item" href="#"><i data-feather="check-square" class="feather-icon"></i>  Validate</a>
                                                <a class="dropdown-item" href="#"><i data-feather="eye" class="feather-icon"></i>  See on site</a>
                                                <a class="dropdown-item" href="#"><i data-feather="edit" class="feather-icon"></i>  Update</a>
                                                <a class="dropdown-item" href="#"><i data-feather="trash-2" class="feather-icon"></i>  Delete</a>
                                                <a class="dropdown-item" href="#"><i data-feather="copy" class="feather-icon"></i>  Duplicate</a>
                                                <a class="dropdown-item" href="#"><i data-feather="send" class="feather-icon"></i>  Contact</a>
                                                <a class="dropdown-item" href="#"><i data-feather="shopping-cart" class="feather-icon"></i>  Suscription</a>
                                            </div>
                                        </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>





{% endblock %}